jobs:
  release:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags
