name: "Docker Release Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker_release:
    name: Call Docker Release Workflow
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: "mbround18/redirect" # Specify the test image name here
      dockerfile: "./Dockerfile" # Path to the seeded Dockerfile
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
